---
name: Test
on: [push]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      - run: npm i
      - uses: ./
        with:
          repository: step-security/harden-runner
      - uses: ./
        with:
          owner: step-security
          repo: harden-runner
      - uses: ./
        with:
          owner: step-security
          repo: harden-runner
          excludes: prerelease, draft
      - uses: ./
        with:
          repository: step-security/harden-runner
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: ./
        with:
          owner: step-security
          repo: harden-runner
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: ./
        with:
          owner: step-security
          repo: harden-runner
          excludes: prerelease, draft
          token: ${{ secrets.GITHUB_TOKEN }}
